// Professional PDF report generation with jsPDF (server-side).
// Layout mirrors the Relu reference: dark header band + amber accent,
// then Company Information, Products & Services, Pain Points, Competitors.

import { jsPDF } from "jspdf";
import type { CompanyReport } from "./types";

const AMBER: [number, number, number] = [230, 168, 63];
const DARK: [number, number, number] = [17, 18, 22];
const TEXT: [number, number, number] = [40, 40, 46];
const MUTED: [number, number, number] = [110, 110, 120];

export function generateReportPdf(report: CompanyReport): Uint8Array {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  const contentW = pageW - margin * 2;
  let y = 0;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - 60) {
      doc.addPage();
      y = margin;
    }
  };

  // ---- Header band ----
  doc.setFillColor(...DARK);
  doc.rect(0, 0, pageW, 120, "F");
  doc.setFillColor(...AMBER);
  doc.rect(0, 120, pageW, 4, "F");

  doc.setTextColor(...AMBER);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("RELU CONSULTANCY · COMPANY RESEARCH REPORT", margin, 48);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(26);
  doc.text(report.name || "Company Report", margin, 84);

  y = 156;

  // ---- Section helper ----
  const sectionTitle = (title: string) => {
    ensureSpace(40);
    doc.setTextColor(...AMBER);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(title.toUpperCase(), margin, y);
    y += 8;
    doc.setDrawColor(225, 225, 230);
    doc.setLineWidth(0.8);
    doc.line(margin, y, pageW - margin, y);
    y += 18;
  };

  const labelValue = (label: string, value: string) => {
    ensureSpace(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...TEXT);
    const lines = doc.splitTextToSize(value || "Not publicly listed", contentW - 110);
    doc.text(lines, margin + 110, y);
    y += Math.max(18, lines.length * 14);
  };

  const bullet = (text: string) => {
    const lines = doc.splitTextToSize(text, contentW - 16);
    ensureSpace(lines.length * 14 + 6);
    doc.setFillColor(...AMBER);
    doc.circle(margin + 3, y - 3, 1.8, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT);
    doc.text(lines, margin + 14, y);
    y += lines.length * 14 + 6;
  };

  // ---- Company Information ----
  sectionTitle("Company Information");
  labelValue("Website", report.website);
  labelValue("Phone", report.phone);
  labelValue("Address", report.address);
  if (report.summary) {
    y += 4;
    labelValue("Summary", report.summary);
  }
  y += 10;

  // ---- Products & Services ----
  if (report.products.length) {
    sectionTitle("Products & Services");
    report.products.forEach((p) => bullet(p));
    y += 10;
  }

  // ---- Pain Points ----
  if (report.painPoints.length) {
    sectionTitle("AI-Generated Pain Points");
    report.painPoints.forEach((p) => bullet(p));
    y += 10;
  }

  // ---- Competitors ----
  if (report.competitors.length) {
    sectionTitle("Competitors");
    report.competitors.forEach((c) => {
      ensureSpace(20);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...TEXT);
      doc.text(c.name, margin, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(70, 90, 180);
      const site = c.website || "—";
      doc.text(site, margin + 180, y);
      y += 18;
    });
    y += 6;
  }

  // ---- Sources ----
  if (report.sources?.length) {
    sectionTitle("Sources");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    report.sources.slice(0, 12).forEach((s) => {
      ensureSpace(12);
      const lines = doc.splitTextToSize(s, contentW);
      doc.text(lines, margin, y);
      y += lines.length * 10;
    });
  }

  // ---- Footer on every page ----
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    const stamp = report.generatedAt
      ? new Date(report.generatedAt).toLocaleString()
      : new Date().toLocaleString();
    doc.text(`Generated by Relu Company Research Assistant · ${stamp}`, margin, pageH - 30);
    doc.text(`${i} / ${pageCount}`, pageW - margin - 20, pageH - 30);
  }

  return new Uint8Array(doc.output("arraybuffer"));
}

export function reportFileName(report: CompanyReport): string {
  const slug = (report.name || "company")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return `${slug || "company"}-research-report.pdf`;
}
